recent code 12

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -135,103 +135,56 @@
 #           path: $GITHUB_WORKSPACE/AutomateCD.ipa
 
 
-# name: Build iOS apps
-
-# on:
-#   push:
-#     paths:
-#       - .github/workflows/build.yml
-
-# jobs:
-#   build_with_signing:
-#     runs-on: macos-latest
-#     steps:
-#       - name: Check Xcode version
-#         run: |
-#           xcode_version=$(xcodebuild -version | grep "Xcode")
-#           if [[ "$xcode_version" =~ "Xcode 13" || "$xcode_version" =~ "Xcode 14" ]]; then
-#             echo "Xcode version is compatible: $xcode_version"
-#           else
-#             echo "Error: Xcode version $xcode_version is not supported. Please use Xcode 13 or above."
-#             exit 1
-#           fi
-#       - name: Decode export options plist
-#         run: |
-#           echo "${{ secrets.EXPORT_OPTIONS_PLIST }}" | base64 --decode > ExportOptions.plist
-#       - name: Checkout repository
-#         uses: actions/checkout@v3
-
-#       - name: Install CocoaPods dependencies
-#         run: |
-#           gem install cocoapods
-#           pod install
-#       - name: Install Apple certificate and provisioning profile
-#         env:
-#           BUILD_CERTIFICATE_BASE64: ${{ secrets.DISTRIBUTION_CERTIFICATE_P12 }}
-#           P12_PASSWORD: ${{ secrets.DISTRIBUTION_CERTIFICATE_PASSWORD }}
-#           BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.APPSTORE_PROVISIONING_PROFILE }}
-#           KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
-#         run: |
-#           CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
-#           PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
-#           KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
-#           echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
-#           echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH
-#           security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
-#           security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
-#           security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
-#           security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
-#           security list-keychain -d user -s $KEYCHAIN_PATH
-#           mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
-#           cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
-#       - name: Generate and archive
-#         run: |
-#           xcodebuild -workspace "AutomateCD.xcworkspace" \
-#           -scheme "AutomateCD" \
-#           -configuration Debug \
-#           -archivePath $RUNNER_TEMP/AutomateCD.xcarchive \
-#           clean archive \
-#           -allowProvisioningUpdates
-#           mv $RUNNER_TEMP/AutomateCD.xcarchive $GITHUB_WORKSPACE
-#       - name: Check if archive exists
-#         run: |
-#           if [ -d "$GITHUB_WORKSPACE/AutomateCD.xcarchive" ]; then
-#             echo "Archive exists"
-#           else
-#             echo "Error: Archive not found"
-#             exit 1
-#           fi
-#       - name: Upload archive as artifact
-#         uses: actions/upload-artifact@v2
-#         with:
-#           name: ios-archive
-#           path: $GITHUB_WORKSPACE/AutomateCD.xcarchive
-#           if-no-files-found: warn
-
-
-
-name: Build and Export iOS App
+name: Build iOS apps
 
 on:
   push:
-    branches:
-      - main
-  pull_request:
-    branches:
-      - main
+    paths:
+      - .github/workflows/build.yml
 
 jobs:
-  build:
+  build_with_signing:
     runs-on: macos-latest
     steps:
-      - uses: actions/checkout@v2
+      - name: Check Xcode version
+        run: |
+          xcode_version=$(xcodebuild -version | grep "Xcode")
+          if [[ "$xcode_version" =~ "Xcode 13" || "$xcode_version" =~ "Xcode 14" ]]; then
+            echo "Xcode version is compatible: $xcode_version"
+          else
+            echo "Error: Xcode version $xcode_version is not supported. Please use Xcode 13 or above."
+            exit 1
+          fi
+      - name: Decode export options plist
+        run: |
+          echo "${{ secrets.EXPORT_OPTIONS_PLIST }}" | base64 --decode > ExportOptions.plist
+      - name: Checkout repository
+        uses: actions/checkout@v3
 
-      - name: Set up CocoaPods
+      - name: Install CocoaPods dependencies
         run: |
           gem install cocoapods
           pod install
-
-      - name: Build and Export iOS App
+      - name: Install Apple certificate and provisioning profile
+        env:
+          BUILD_CERTIFICATE_BASE64: ${{ secrets.DISTRIBUTION_CERTIFICATE_P12 }}
+          P12_PASSWORD: ${{ secrets.DISTRIBUTION_CERTIFICATE_PASSWORD }}
+          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.APPSTORE_PROVISIONING_PROFILE }}
+          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
+        run: |
+          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
+          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
+          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
+          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
+          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH
+          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
+          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
+          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
+          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
+          security list-keychain -d user -s $KEYCHAIN_PATH
+          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
+          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
+      - name: Generate and archive
         run: |
           xcodebuild -workspace "AutomateCD.xcworkspace" \
           -scheme "AutomateCD" \
@@ -239,23 +192,18 @@ jobs:
           -archivePath $RUNNER_TEMP/AutomateCD.xcarchive \
           clean archive \
           -allowProvisioningUpdates
-          # Export IPA without ExportOptions.plist
-          echo "Runner temp path: $RUNNER_TEMP"
-          xcodebuild -exportArchive -archivePath $RUNNER_TEMP/AutomateCD.xcarchive \
-          -exportOptionsPlist \
-          '{ \
-            "method": "app-store", \
-            "signingStyle": "automatic", \
-            "stripSwiftSymbols": true, \
-            "destination": "export" \
-          }' \
-          -exportPath $RUNNER_TEMP/build
-          echo "Runner temp path1: $RUNNER_TEMP"
-          # Move IPA to workspace
-          mv $RUNNER_TEMP/build/AutomateCD.ipa $GITHUB_WORKSPACE
-
-      - name: Upload IPA as artifact
+          mv $RUNNER_TEMP/AutomateCD.xcarchive $GITHUB_WORKSPACE
+      - name: Check if archive exists
+        run: |
+          if [ -d "$GITHUB_WORKSPACE/AutomateCD.xcarchive" ]; then
+            echo "Archive exists"
+          else
+            echo "Error: Archive not found"
+            exit 1
+          fi
+      - name: Upload archive as artifact
         uses: actions/upload-artifact@v2
         with:
-          name: ios-app
-          path: $GITHUB_WORKSPACE/AutomateCD.ipa
+          name: ios-archive
+          path: $GITHUB_WORKSPACE/AutomateCD.xcarchive
+          if-no-files-found: warn
